# Generate header dependencies during compilation preprocessing.
CPPFLAGS = -MMD
# the usual...
CXXFLAGS = --std=c++20 -O2 -Wall -Wextra -pedantic -Werror

.PHONY: all
all: diagrams/foobar.svg diagrams/mary.svg

huffer: huffer.o
	$(CXX) -o $@ $^

%.svg: %.txt huffer
	./huffer graph $< | dot -Tsvg >$@

# Include the make targets that were generated by the implicit %.o rule, which
# will invoke the C++ compiler and pass it the CPPFLAGS preprocessor flags,
# which contain the "-MMD" argument, which produces a *.d file that relates
# sources to header files included by them.
-include *.d
